### ISSUE TITLE
search/embedsearch for 'Derek's Book' not returning as expected

### ISSUE THREAD

**Issue by leovander** [Gelean/deldbot#1]
**Expected**
```
!search derek's book
Fuck you

!embedsearch derek's book
Fuck you
```

**Actual**
```
!search derek's book
No results found, please refine your search dimwit

!embedsearch derek's book
No results found, please refine your search dimwit
```

https://github.com/Gelean/deldbot/blob/7d0146fcd3a4daf5e665700b38c78b7369d5ea4a/bot.js#L183
https://github.com/Gelean/deldbot/blob/7d0146fcd3a4daf5e665700b38c78b7369d5ea4a/bot.js#L255

![image](https://user-images.githubusercontent.com/4349174/67790132-77feb200-fa32-11e9-977e-6d5497da5d7f.png)

Not necessarily part of the issue, more of an improvement, but you could condense your if statements with regex to handle both cases. e.g. `[dD]erek'?s [bB]ook`.

**Comment by leovander** [comment]
@Gelean 
Ah, maybe trying taking a look at the `query.join(' ')` that I had mentioned in chat. This is probably failing because you have an extra empty space tacked onto the end of the string so its `derek's book_` instead of `derek's book`.

https://github.com/Gelean/deldbot/blob/7d0146fcd3a4daf5e665700b38c78b7369d5ea4a/bot.js#L178
https://github.com/Gelean/deldbot/blob/7d0146fcd3a4daf5e665700b38c78b7369d5ea4a/bot.js#L250

Alternatively, you can `trim` query to that it gets rid of your starting/trailing white spaces.

**Comment by Gelean** [comment]
Did some code cleanup in 9567ecc10dbb565fa318923d4c827daef62b29fa and this should be fixed now

Thanks again for the help on this @leovander
