### ISSUE TITLE
Reduce repeated calls to message.channel.send in Roll command

### ISSUE THREAD

**Issue by leovander** [Gelean/deldbot#28]
Add a new placeholder final text before this block. Make the else statement the default case and only have your if statement for the ones that need changing.

https://github.com/Gelean/deldbot/blob/5f8bce1bcd788ddc5f7493452d004667c9bec919/src/commands/roll.js#L15-L20

Rework this section to not use a for loop, you can use verbose to get back an array of all the rolls, and you can use a `.toString()` or `.join()` to list them all out in your single message.

https://github.com/Gelean/deldbot/blob/5f8bce1bcd788ddc5f7493452d004667c9bec919/src/commands/roll.js#L22-L44

**Comment by Gelean** [comment]
Improved considerably in e3b2c5f45595a5c7d239a26070ce0a93398a1dbd, thanks Israel
